//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoUIMvcApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product : VersionedEntity
    {
        public Product()
        {
            //this.Order_Details = new HashSet<Order_Detail>();
        }
    
        //public int ProductID { get; set; }
        public string ProductName { get; set; }
        private int? supplierID;
        public Nullable<int> SupplierID 
        {
            get
            {
                if(Supplier == null)
                {
                    return supplierID;
                }
                return Supplier.Id;
            }
            set
            {
                supplierID = value;
                if(Supplier != null)
                {
                    Supplier.Id = value.GetValueOrDefault();
                }
            }
        }
        private int? categoryID;
        public Nullable<int> CategoryID
        {
            get
            {
                if(Category == null)
                {
                    return categoryID;
                }
                return Category.Id;
            }
            set
            {
                categoryID = value;
                if(Category != null)
                {
                    Category.Id = value.GetValueOrDefault();
                }
            }
        }
        public string QuantityPerUnit { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<short> UnitsInStock { get; set; }
        public Nullable<short> UnitsOnOrder { get; set; }
        public Nullable<short> ReorderLevel { get; set; }
        public bool Discontinued { get; set; }
    
        public virtual Category Category { get; set; }
        //public ICollection<Order_Detail> Order_Details { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
